### ISSUE TITLE
Missing definition of $h$ in the Chemical reactor example

### ISSUE THREAD

**Issue by pierre-haessig** [nMPyC/nmpyc#1]
Hi,

I just came across your nice nMPyC project thanks a colleague.

While reading the [Chemical reactor](https://nmpyc.readthedocs.io/en/latest/example/reactor.html) example, which is nice, I noticed that the parameter $h$ is not defined. 

Now, I infer from the rest of the document that h is the timestep and h=0.5 min (since time unit is min, correct?). If this is so, I would add it after the dynamical equations, along the definition of c_A, Q... and/or in the table. Also, I think `h` should be used in the code implemenation (where I found a 0.5 hard coded to infer the value of h)

Apart from that, I would make the following sentence more explicit: "and is given by the nonlinear model" → "and is given by the *discrete time* nonlinear model", even though this fact becomes apparent after reading the equation.

Also, I would take out the equilbrium point from the table "Reactor constants" since it's the outcome of a (omitted) computation rather that a free parameter of the model. Someithing like "from this set of parameters, we can compute equilibrium $(c_A,c_B,Q) = (1/2, 1/2, 12)$"

**Comment by JoSchiessl** [comment]
Thank you for your feedback and reading the documentation so carefully. I have edited the reactor example according to your suggestions and the new version should now be available online.

**Comment by pierre-haessig** [comment]
You're welcome!
